//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PP.AppData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class school5Entities2 : DbContext
    {
        public school5Entities2()
            : base("name=school5Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClassTeachers> ClassTeachers { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<Grades_Class5A> Grades_Class5A { get; set; }
        public virtual DbSet<Grades_Class6A> Grades_Class6A { get; set; }
        public virtual DbSet<Grades_Class7A> Grades_Class7A { get; set; }
        public virtual DbSet<Grades_Class8A> Grades_Class8A { get; set; }
        public virtual DbSet<Students5A> Students5A { get; set; }
        public virtual DbSet<Students6A> Students6A { get; set; }
        public virtual DbSet<Students7A> Students7A { get; set; }
        public virtual DbSet<Students8A> Students8A { get; set; }
        public virtual DbSet<Subjects5A> Subjects5A { get; set; }
        public virtual DbSet<Subjects6A> Subjects6A { get; set; }
        public virtual DbSet<Subjects7A> Subjects7A { get; set; }
        public virtual DbSet<Subjects8A> Subjects8A { get; set; }
    }
}
